cmake_minimum_required(VERSION 3.16)

function(set_test_output target group)
    set_target_properties(${target} PROPERTIES
        RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin/tests/${group}"
    )
endfunction()

function(set_diag_output target group)
    set_target_properties(${target} PROPERTIES
        RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin/diag/${group}"
    )
endfunction()

add_executable(auto_aim_test auto_aim/auto_aim_test.cpp)
add_executable(auto_power_rune_test auto_buff/auto_power_rune_test.cpp)
add_executable(camera_detect_test camera/camera_detect_test.cpp)
add_executable(camera_test camera/camera_test.cpp)
add_executable(camera_save_test camera/camera_save_test.cpp)
add_executable(camera_thread_test camera/camera_thread_test.cpp)
add_executable(camera_window_test camera/camera_window_test.cpp)
add_executable(cboard_test system/cboard_test.cpp)
add_executable(fire_test auto_aim/fire_test.cpp)
add_executable(detector_video_test auto_aim/detector_video_test.cpp)
add_executable(gimbal_response_test gimbal/gimbal_response_test.cpp)
add_executable(multi_usbcamera_test camera/multi_usbcamera_test.cpp)
add_executable(usbcamera_detect_test camera/usbcamera_detect_test.cpp)
add_executable(usbcamera_test camera/usbcamera_test.cpp)
add_executable(handeye_test camera/handeye_test.cpp)
add_executable(dm_test system/dm_test.cpp)
add_executable(gimbal_test gimbal/gimbal_test.cpp)
add_executable(planner_test planner/planner_test.cpp)
add_executable(planner_test_offline planner/planner_test_offline.cpp)

target_link_libraries(auto_aim_test ${OpenCV_LIBS} fmt::fmt yaml-cpp io auto_aim tools)
target_link_libraries(auto_power_rune_test ${OpenCV_LIBS} fmt::fmt yaml-cpp auto_buff io tools)
target_link_libraries(camera_detect_test ${OpenCV_LIBS} fmt::fmt yaml-cpp auto_aim io tools)
target_link_libraries(camera_test ${OpenCV_LIBS} fmt::fmt io tools)
target_link_libraries(camera_save_test ${OpenCV_LIBS} fmt::fmt io tools)
target_link_libraries(camera_thread_test ${OpenCV_LIBS} fmt::fmt auto_aim io tools)
target_link_libraries(camera_window_test ${OpenCV_LIBS} fmt::fmt io tools)
target_link_libraries(cboard_test ${OpenCV_LIBS} fmt::fmt io tools)
target_link_libraries(fire_test ${OpenCV_LIBS} fmt::fmt io tools)
target_link_libraries(detector_video_test ${OpenCV_LIBS} fmt::fmt yaml-cpp auto_aim tools)
target_link_libraries(gimbal_response_test ${OpenCV_LIBS} fmt::fmt yaml-cpp io tools)
target_link_libraries(multi_usbcamera_test ${OpenCV_LIBS} fmt::fmt io tools)
target_link_libraries(usbcamera_detect_test ${OpenCV_LIBS} fmt::fmt yaml-cpp auto_aim io tools)
target_link_libraries(usbcamera_test ${OpenCV_LIBS} fmt::fmt yaml-cpp io tools)
target_link_libraries(handeye_test ${OpenCV_LIBS} fmt::fmt yaml-cpp auto_aim io tools)
target_link_libraries(dm_test ${OpenCV_LIBS} fmt::fmt yaml-cpp io tools)
target_link_libraries(gimbal_test ${OpenCV_LIBS} fmt::fmt yaml-cpp auto_aim io tools)
target_link_libraries(planner_test ${OpenCV_LIBS} fmt::fmt yaml-cpp auto_aim io tools)
target_link_libraries(planner_test_offline ${OpenCV_LIBS} fmt::fmt yaml-cpp auto_aim io tools)

set_test_output(auto_aim_test auto_aim)
set_test_output(detector_video_test auto_aim)
set_test_output(fire_test auto_aim)

set_test_output(auto_power_rune_test auto_buff)

set_test_output(camera_detect_test camera)
set_test_output(camera_test camera)
set_test_output(camera_save_test camera)
set_test_output(camera_thread_test camera)
set_test_output(camera_window_test camera)
set_test_output(usbcamera_detect_test camera)
set_test_output(usbcamera_test camera)
set_test_output(multi_usbcamera_test camera)
set_test_output(handeye_test camera)

set_test_output(gimbal_test gimbal)
set_test_output(gimbal_response_test gimbal)

set_test_output(planner_test planner)
set_test_output(planner_test_offline planner)

set_test_output(cboard_test system)
set_test_output(dm_test system)

if(ament_cmake_FOUND AND rclcpp_FOUND AND std_msgs_FOUND AND rosidl_typesupport_cpp_FOUND AND sp_msgs_FOUND)
    add_subdirectory(ros2)
else()
    message(STATUS "ROS2 environment not found, skipping ROS2-related test code.")
endif()
