# handeye_test 模板配置
# 需要按实际机器人修改相机、C 板与外参参数。

enemy_color: "blue"

#####-----手眼投影参数-----#####
height: 0.60
grid_num: 6
grid_size: 0.10
delay: 0

#####-----神经网络参数-----#####
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/yolov5.xml
device: CPU
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi:
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 15
outpost_max_temp_lost_count: 75

#####-----aimer参数-----#####
yaw_offset: 2
pitch_offset: 13
comming_angle: 55
leaving_angle: 20
decision_speed: 7
high_speed_delay_time: 0.0
low_speed_delay_time: 0.0

#####-----shooter参数-----#####
first_tolerance: 3
second_tolerance: 2
judge_distance: 2
auto_fire: true

camera_name: "hikrobot"
exposure_ms: 2.0
gain: 16.9
vid_pid: "2bdf:0001"

R_gimbal2imubody: [0, -1, 0, 1, 0, 0, 0, 0, 1]

camera_matrix: [2297.9076211852957, 0, 708.904811632396, 0, 2310.18700574314, 473.73138749214627, 0, 0, 1]
distort_coeffs: [-0.022724092108620295, -0.08712931172497097, 0.0005902524029876164, -0.0015723013201643706, 0]

R_camera2gimbal: [-0.02718211903023091, -0.12616154330853446, 0.9916372307426918, -0.9994910655751733, 0.019998323121329122, -0.024853106601381177, -0.016695575474690555, -0.9918081125209369, -0.12664093215554434]
t_camera2gimbal: [0.13160669975045827, 0.10377721766577375, 0.024908271912914642]

#####-----cboard参数-----#####
quaternion_canid: 0x100
bullet_speed_canid: 0x101
send_canid: 0xff
can_interface: "can0"

#####-----gimbal参数-----#####
com_port: "/dev/ttyACM0"
gimbal_transport: "serial"
gimbal_to_vision_topic: "/gimbal_to_vision"
vision_to_gimbal_topic: "/vision_to_gimbal"
gimbal_ros2_node_name: "sp_vision_gimbal_transport"
yaw_kp: 0
yaw_kd: 0
pitch_kp: 0
pitch_kd: 0
