enemy_color: "red"

#####-----神经网络参数-----#####
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/yolov5.xml
device: CPU
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 15
outpost_max_temp_lost_count: 75

#####-----aimer参数-----#####
yaw_offset: 180 # degree -2.5
pitch_offset: 0 # degree 2
comming_angle: 55 # degree
leaving_angle: 20 # degree
decision_speed: 7 # rad/s
high_speed_delay_time: 0.0 # s
low_speed_delay_time: 0.0 # s planner use this value

#####-----shooter参数-----#####
first_tolerance: 3 # 近距离射击容差，degree
second_tolerance: 2 # 远距离射击容差，degree
judge_distance: 2 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

camera_name: "hikrobot"
exposure_ms: 2.000000
gain: 16.9
vid_pid: "2bdf:0001"

#  1  0  0
#  0  1  0
#  0  0  1
R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]


# 重投影误差: 0.0642px
camera_matrix: [2297.9076211852957, 0, 708.90481163239599, 0, 2310.1870057431402, 473.73138749214627, 0, 0, 1]
distort_coeffs: [-0.022724092108620295, -0.087129311724970973, 0.00059025240298761635, -0.0015723013201643706, 0]

# 相机同理想情况的偏角: yaw-175.50 pitch-0.50 roll8.98 degree
# 标定板到世界坐标系原点的水平距离: 0.14 m
# 标定板同竖直摆放时的偏角: yaw28.56 pitch3.86 roll8.27 degree
R_camera2gimbal: [0.079125208417017562, -0.0036283822032382503, -0.99685808229434092, 0.98457503872694296, -0.15625400742507073, 0.078718982967545467, -0.1560486927494181, -0.98771024091389936, -0.0087912163552334461]
t_camera2gimbal: [0.64218682308034336, 0.026127386912401469, 0.049847783822523903]


#####-----cboard参数-----#####
quaternion_canid: 0x100
bullet_speed_canid: 0x101
send_canid: 0xff
can_interface: "can0"

#####-----gimbal参数-----#####
com_port: "/dev/ttyACM0"
yaw_kp: 0
yaw_kd: 0
pitch_kp: 0
pitch_kd: 0

#####-----planner-----#####
fire_thresh: 0.0035

max_yaw_acc: 50
Q_yaw: [9e6, 0]
R_yaw: [1]

max_pitch_acc: 100
Q_pitch: [9e6, 0]
R_pitch: [1]

#####-----buff_detector参数-----#####
model: "assets/yolo11_buff_int8.xml"

#####-----buff_aimer参数-----#####
fire_gap_time: 0.700   # s
predict_time: 0.120     # s
