function(set_app_output target group)
    set_target_properties(${target} PROPERTIES
        RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin/apps/${group}"
    )
endfunction()

add_executable(standard standard.cpp)
add_executable(mt_standard mt_standard.cpp)
add_executable(standard_mpc standard_mpc.cpp)
add_executable(auto_aim_debug_mpc auto_aim_debug_mpc.cpp)
add_executable(mt_auto_aim_debug mt_auto_aim_debug.cpp)
add_executable(auto_buff_debug auto_buff_debug.cpp)
add_executable(auto_buff_debug_mpc auto_buff_debug_mpc.cpp)
add_executable(uav uav.cpp)
add_executable(uav_debug uav_debug.cpp)

target_link_libraries(standard ${OpenCV_LIBS} fmt::fmt yaml-cpp auto_aim auto_buff io tools)
target_link_libraries(mt_standard ${OpenCV_LIBS} fmt::fmt yaml-cpp auto_aim auto_buff io tools)
target_link_libraries(standard_mpc ${OpenCV_LIBS} fmt::fmt yaml-cpp auto_aim auto_buff io tools)
target_link_libraries(auto_aim_debug_mpc ${OpenCV_LIBS} fmt::fmt yaml-cpp auto_aim auto_buff io tools)
target_link_libraries(mt_auto_aim_debug ${OpenCV_LIBS} fmt::fmt yaml-cpp auto_aim auto_buff io tools)
target_link_libraries(auto_buff_debug ${OpenCV_LIBS} fmt::fmt yaml-cpp auto_buff io tools ${CERES_LIBRARIES})
target_link_libraries(auto_buff_debug_mpc ${OpenCV_LIBS} fmt::fmt yaml-cpp auto_buff io tools ${CERES_LIBRARIES})
target_link_libraries(uav ${OpenCV_LIBS} fmt::fmt yaml-cpp auto_aim auto_buff io tools)
target_link_libraries(uav_debug ${OpenCV_LIBS} fmt::fmt yaml-cpp auto_aim io tools)

set_app_output(standard standard)
set_app_output(mt_standard standard)
set_app_output(standard_mpc standard)
set_app_output(auto_aim_debug_mpc debug)
set_app_output(mt_auto_aim_debug debug)
set_app_output(auto_buff_debug debug)
set_app_output(auto_buff_debug_mpc debug)
set_app_output(uav uav)
set_app_output(uav_debug debug)

# 只有在找到 ROS 环境时才会添加 sentry 系列入口
if(ament_cmake_FOUND AND rclcpp_FOUND AND std_msgs_FOUND AND rosidl_typesupport_cpp_FOUND AND sp_msgs_FOUND)
    add_executable(sentry ../src/sentry.cpp)
    add_executable(sentry_bp ../src/sentry_bp.cpp)
    add_executable(sentry_debug ../src/sentry_debug.cpp)
    add_executable(sentry_multithread ../src/sentry_multithread.cpp)

    target_link_libraries(sentry ${OpenCV_LIBS} fmt::fmt yaml-cpp auto_aim omniperception tools io)
    target_link_libraries(sentry_bp ${OpenCV_LIBS} fmt::fmt yaml-cpp auto_aim omniperception tools io)
    target_link_libraries(sentry_debug ${OpenCV_LIBS} fmt::fmt yaml-cpp auto_aim omniperception tools io)
    target_link_libraries(sentry_multithread ${OpenCV_LIBS} fmt::fmt yaml-cpp auto_aim omniperception tools io)

    set_app_output(sentry sentry)
    set_app_output(sentry_bp sentry)
    set_app_output(sentry_debug sentry)
    set_app_output(sentry_multithread sentry)
endif()
